### ISSUE TITLE
Create handlebar templates

### ISSUE THREAD

**Issue by rebeccalehew** [SChafinIII/Mad-Libs#24]
- main.handlebars
- homepage.handlebars
- login.handlebars
- blanks.handlebars
- madlib.handlebars
- partials > mary-lamb.handlebars
- partials > row-row.handlebars

**Comment by rebeccalehew** [comment]
login.handlebars completed

**Comment by SChafinIII** [comment]
main.handlebars adjusted. 
login.handlebars adjusted.

**Comment by rebeccalehew** [comment]
Steven and Rebecca knocked out the rest of the handlebars. Cole added a completed-radlibs.handlebars to show all the radlibs a user creates.
